use nodedb;

CREATE TABLE IF NOT EXISTS PEOPLE(ID INT NOT NULL AUTO_INCREMENT, NAME VARCHAR(255), PRIMARY KEY(ID));
--CREATE TABLE IF NOT EXISTS `characterSW`(`id` int NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, PRIMARY KEY(`id`));